#define MAX_ROOMS 16
#define MAX_USER_PER_ROOM 16
#define SERVER_CAPACITY (MAX_ROOMS * MAX_USER_PER_ROOM)

#define LISTENQUEUE 10

#define BUFFERSIZE 2048

#define MAX_USERNAME 10
#define MAX_ROOMNAME 10
